// <auto-generated />
using System;
using Backed.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backed.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251108025615_SeedAdminRoleMenus")]
    partial class SeedAdminRoleMenus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backed.Domain.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "dashboard",
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2231),
                            Icon = "ViewDashboard",
                            IsActive = true,
                            Name = "仪表盘",
                            Path = "/dashboard",
                            SortOrder = 1,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2231)
                        },
                        new
                        {
                            Id = 2,
                            Code = "products",
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2234),
                            Icon = "PackageVariant",
                            IsActive = true,
                            Name = "商品管理",
                            Path = "/products",
                            SortOrder = 2,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2235)
                        },
                        new
                        {
                            Id = 3,
                            Code = "product_list",
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2238),
                            Icon = "FormatListBulleted",
                            IsActive = true,
                            Name = "商品列表",
                            ParentId = 2,
                            Path = "/products/list",
                            SortOrder = 1,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2238)
                        },
                        new
                        {
                            Id = 4,
                            Code = "product_category",
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2241),
                            Icon = "Folder",
                            IsActive = true,
                            Name = "商品分类",
                            ParentId = 2,
                            Path = "/products/category",
                            SortOrder = 2,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2241)
                        },
                        new
                        {
                            Id = 5,
                            Code = "orders",
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2243),
                            Icon = "ClipboardList",
                            IsActive = true,
                            Name = "订单管理",
                            Path = "/orders",
                            SortOrder = 3,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2244)
                        },
                        new
                        {
                            Id = 6,
                            Code = "order_list",
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2246),
                            Icon = "FormatListBulleted",
                            IsActive = true,
                            Name = "订单列表",
                            ParentId = 5,
                            Path = "/orders/list",
                            SortOrder = 1,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2247)
                        },
                        new
                        {
                            Id = 7,
                            Code = "order_returns",
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2249),
                            Icon = "PackageDown",
                            IsActive = true,
                            Name = "退货申请",
                            ParentId = 5,
                            Path = "/orders/returns",
                            SortOrder = 2,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2249)
                        },
                        new
                        {
                            Id = 8,
                            Code = "members",
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2252),
                            Icon = "AccountMultiple",
                            IsActive = true,
                            Name = "会员管理",
                            Path = "/members",
                            SortOrder = 4,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2252)
                        },
                        new
                        {
                            Id = 9,
                            Code = "member_list",
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2255),
                            Icon = "FormatListBulleted",
                            IsActive = true,
                            Name = "会员列表",
                            ParentId = 8,
                            Path = "/members/list",
                            SortOrder = 1,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2255)
                        },
                        new
                        {
                            Id = 10,
                            Code = "member_levels",
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2258),
                            Icon = "Star",
                            IsActive = true,
                            Name = "会员等级",
                            ParentId = 8,
                            Path = "/members/levels",
                            SortOrder = 2,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2258)
                        },
                        new
                        {
                            Id = 11,
                            Code = "settings",
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2261),
                            Icon = "Cog",
                            IsActive = true,
                            Name = "系统设置",
                            Path = "/settings",
                            SortOrder = 5,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2261)
                        },
                        new
                        {
                            Id = 12,
                            Code = "user_management",
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2264),
                            Icon = "Account",
                            IsActive = true,
                            Name = "用户管理",
                            ParentId = 11,
                            Path = "/settings/users",
                            SortOrder = 1,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2264)
                        },
                        new
                        {
                            Id = 13,
                            Code = "role_management",
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2266),
                            Icon = "AccountArrowRight",
                            IsActive = true,
                            Name = "角色管理",
                            ParentId = 11,
                            Path = "/settings/roles",
                            SortOrder = 2,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2267)
                        },
                        new
                        {
                            Id = 14,
                            Code = "menu_management",
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2269),
                            Icon = "Menu",
                            IsActive = true,
                            Name = "菜单管理",
                            ParentId = 11,
                            Path = "/settings/menus",
                            SortOrder = 3,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2270)
                        });
                });

            modelBuilder.Entity("Backed.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2055),
                            Description = "Can view dashboard",
                            Name = "ViewDashboard",
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2056)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2059),
                            Description = "Can manage users",
                            Name = "ManageUsers",
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2060)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2062),
                            Description = "Can manage roles",
                            Name = "ManageRoles",
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2062)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2064),
                            Description = "Can manage products",
                            Name = "ManageProducts",
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2065)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2066),
                            Description = "Can manage menus",
                            Name = "ManageMenus",
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2071)
                        });
                });

            modelBuilder.Entity("Backed.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(1839),
                            Description = "Administrator role with full access",
                            Name = "Admin",
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(1839)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(1842),
                            Description = "Regular user role",
                            Name = "User",
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(1843)
                        });
                });

            modelBuilder.Entity("Backed.Domain.Entities.RoleMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("RoleId", "MenuId")
                        .IsUnique();

                    b.ToTable("RoleMenus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2365),
                            MenuId = 1,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2366)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2378),
                            MenuId = 2,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2379)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2380),
                            MenuId = 3,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2380)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2381),
                            MenuId = 4,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2382)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2383),
                            MenuId = 5,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2383)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2385),
                            MenuId = 6,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2385)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2386),
                            MenuId = 7,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2387)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2388),
                            MenuId = 8,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2388)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2389),
                            MenuId = 9,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2390)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2391),
                            MenuId = 10,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2392)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2393),
                            MenuId = 11,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2393)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2394),
                            MenuId = 12,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2395)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2396),
                            MenuId = 13,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2396)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2397),
                            MenuId = 14,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2397)
                        });
                });

            modelBuilder.Entity("Backed.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2114),
                            PermissionId = 1,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2114)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2116),
                            PermissionId = 2,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2116)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2118),
                            PermissionId = 3,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2118)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2120),
                            PermissionId = 4,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2121)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2122),
                            PermissionId = 5,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2123)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2166),
                            PermissionId = 1,
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2166)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2168),
                            PermissionId = 4,
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2168)
                        });
                });

            modelBuilder.Entity("Backed.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2291),
                            Email = "admin@example.com",
                            IsActive = true,
                            PasswordHash = "21232f297a57a5a743894a0e4a801fc3",
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2291),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Backed.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2356),
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 8, 2, 56, 12, 99, DateTimeKind.Utc).AddTicks(2357),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Backed.Domain.Entities.Menu", b =>
                {
                    b.HasOne("Backed.Domain.Entities.Menu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Backed.Domain.Entities.RoleMenu", b =>
                {
                    b.HasOne("Backed.Domain.Entities.Menu", "Menu")
                        .WithMany("RoleMenus")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backed.Domain.Entities.Role", "Role")
                        .WithMany("RoleMenus")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Backed.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Backed.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backed.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Backed.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Backed.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backed.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backed.Domain.Entities.Menu", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("RoleMenus");
                });

            modelBuilder.Entity("Backed.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Backed.Domain.Entities.Role", b =>
                {
                    b.Navigation("RoleMenus");

                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Backed.Domain.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
