// <auto-generated />
using System;
using Backed.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backed.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251106064109_AddMenuManagementPermission")]
    partial class AddMenuManagementPermission
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backed.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 6, 6, 41, 8, 287, DateTimeKind.Utc).AddTicks(8942),
                            Description = "Can view dashboard",
                            Name = "ViewDashboard",
                            UpdatedAt = new DateTime(2025, 11, 6, 6, 41, 8, 287, DateTimeKind.Utc).AddTicks(8943)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 6, 6, 41, 8, 287, DateTimeKind.Utc).AddTicks(8946),
                            Description = "Can manage users",
                            Name = "ManageUsers",
                            UpdatedAt = new DateTime(2025, 11, 6, 6, 41, 8, 287, DateTimeKind.Utc).AddTicks(8946)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 6, 6, 41, 8, 287, DateTimeKind.Utc).AddTicks(8948),
                            Description = "Can manage roles",
                            Name = "ManageRoles",
                            UpdatedAt = new DateTime(2025, 11, 6, 6, 41, 8, 287, DateTimeKind.Utc).AddTicks(8948)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 11, 6, 6, 41, 8, 287, DateTimeKind.Utc).AddTicks(8950),
                            Description = "Can manage products",
                            Name = "ManageProducts",
                            UpdatedAt = new DateTime(2025, 11, 6, 6, 41, 8, 287, DateTimeKind.Utc).AddTicks(8951)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 11, 6, 6, 41, 8, 287, DateTimeKind.Utc).AddTicks(8953),
                            Description = "Can manage menus",
                            Name = "ManageMenus",
                            UpdatedAt = new DateTime(2025, 11, 6, 6, 41, 8, 287, DateTimeKind.Utc).AddTicks(8953)
                        });
                });

            modelBuilder.Entity("Backed.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 6, 6, 41, 8, 287, DateTimeKind.Utc).AddTicks(8618),
                            Description = "Administrator role with full access",
                            Name = "Admin",
                            UpdatedAt = new DateTime(2025, 11, 6, 6, 41, 8, 287, DateTimeKind.Utc).AddTicks(8619)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 6, 6, 41, 8, 287, DateTimeKind.Utc).AddTicks(8621),
                            Description = "Regular user role",
                            Name = "User",
                            UpdatedAt = new DateTime(2025, 11, 6, 6, 41, 8, 287, DateTimeKind.Utc).AddTicks(8622)
                        });
                });

            modelBuilder.Entity("Backed.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 6, 6, 41, 8, 287, DateTimeKind.Utc).AddTicks(8984),
                            PermissionId = 1,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 6, 6, 41, 8, 287, DateTimeKind.Utc).AddTicks(8984)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 6, 6, 41, 8, 287, DateTimeKind.Utc).AddTicks(8987),
                            PermissionId = 2,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 6, 6, 41, 8, 287, DateTimeKind.Utc).AddTicks(8987)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 6, 6, 41, 8, 287, DateTimeKind.Utc).AddTicks(8989),
                            PermissionId = 3,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 6, 6, 41, 8, 287, DateTimeKind.Utc).AddTicks(8989)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 11, 6, 6, 41, 8, 287, DateTimeKind.Utc).AddTicks(8991),
                            PermissionId = 4,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 6, 6, 41, 8, 287, DateTimeKind.Utc).AddTicks(8991)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 11, 6, 6, 41, 8, 287, DateTimeKind.Utc).AddTicks(8993),
                            PermissionId = 5,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 6, 6, 41, 8, 287, DateTimeKind.Utc).AddTicks(8994)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 11, 6, 6, 41, 8, 287, DateTimeKind.Utc).AddTicks(8995),
                            PermissionId = 1,
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 11, 6, 6, 41, 8, 287, DateTimeKind.Utc).AddTicks(8996)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 11, 6, 6, 41, 8, 287, DateTimeKind.Utc).AddTicks(8997),
                            PermissionId = 4,
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 11, 6, 6, 41, 8, 287, DateTimeKind.Utc).AddTicks(8998)
                        });
                });

            modelBuilder.Entity("Backed.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 6, 6, 41, 8, 287, DateTimeKind.Utc).AddTicks(9011),
                            Email = "admin@example.com",
                            IsActive = true,
                            PasswordHash = "21232f297a57a5a743894a0e4a801fc3",
                            UpdatedAt = new DateTime(2025, 11, 6, 6, 41, 8, 287, DateTimeKind.Utc).AddTicks(9011),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Backed.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 6, 6, 41, 8, 287, DateTimeKind.Utc).AddTicks(9050),
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 6, 6, 41, 8, 287, DateTimeKind.Utc).AddTicks(9051),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Backed.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Backed.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backed.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Backed.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Backed.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backed.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backed.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Backed.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Backed.Domain.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
