// <auto-generated />
using System;
using Backed.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backed.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251107082118_AddRoleMenuEntity")]
    partial class AddRoleMenuEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backed.Domain.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "dashboard",
                            CreatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3213),
                            Icon = "ViewDashboard",
                            IsActive = true,
                            Name = "仪表盘",
                            Path = "/dashboard",
                            SortOrder = 1,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3214)
                        },
                        new
                        {
                            Id = 2,
                            Code = "products",
                            CreatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3217),
                            Icon = "PackageVariant",
                            IsActive = true,
                            Name = "商品管理",
                            Path = "/products",
                            SortOrder = 2,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3218)
                        },
                        new
                        {
                            Id = 3,
                            Code = "product_list",
                            CreatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3221),
                            Icon = "FormatListBulleted",
                            IsActive = true,
                            Name = "商品列表",
                            ParentId = 2,
                            Path = "/products/list",
                            SortOrder = 1,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3221)
                        },
                        new
                        {
                            Id = 4,
                            Code = "product_category",
                            CreatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3224),
                            Icon = "Folder",
                            IsActive = true,
                            Name = "商品分类",
                            ParentId = 2,
                            Path = "/products/category",
                            SortOrder = 2,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3224)
                        },
                        new
                        {
                            Id = 5,
                            Code = "orders",
                            CreatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3226),
                            Icon = "ClipboardList",
                            IsActive = true,
                            Name = "订单管理",
                            Path = "/orders",
                            SortOrder = 3,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3227)
                        },
                        new
                        {
                            Id = 6,
                            Code = "order_list",
                            CreatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3229),
                            Icon = "FormatListBulleted",
                            IsActive = true,
                            Name = "订单列表",
                            ParentId = 5,
                            Path = "/orders/list",
                            SortOrder = 1,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3230)
                        },
                        new
                        {
                            Id = 7,
                            Code = "order_returns",
                            CreatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3232),
                            Icon = "PackageDown",
                            IsActive = true,
                            Name = "退货申请",
                            ParentId = 5,
                            Path = "/orders/returns",
                            SortOrder = 2,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3233)
                        },
                        new
                        {
                            Id = 8,
                            Code = "members",
                            CreatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3235),
                            Icon = "AccountMultiple",
                            IsActive = true,
                            Name = "会员管理",
                            Path = "/members",
                            SortOrder = 4,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3235)
                        },
                        new
                        {
                            Id = 9,
                            Code = "member_list",
                            CreatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3238),
                            Icon = "FormatListBulleted",
                            IsActive = true,
                            Name = "会员列表",
                            ParentId = 8,
                            Path = "/members/list",
                            SortOrder = 1,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3238)
                        },
                        new
                        {
                            Id = 10,
                            Code = "member_levels",
                            CreatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3241),
                            Icon = "Star",
                            IsActive = true,
                            Name = "会员等级",
                            ParentId = 8,
                            Path = "/members/levels",
                            SortOrder = 2,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3241)
                        },
                        new
                        {
                            Id = 11,
                            Code = "settings",
                            CreatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(5143),
                            Icon = "Cog",
                            IsActive = true,
                            Name = "系统设置",
                            Path = "/settings",
                            SortOrder = 5,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(5144)
                        },
                        new
                        {
                            Id = 12,
                            Code = "user_management",
                            CreatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(5149),
                            Icon = "Account",
                            IsActive = true,
                            Name = "用户管理",
                            ParentId = 11,
                            Path = "/settings/users",
                            SortOrder = 1,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(5149)
                        },
                        new
                        {
                            Id = 13,
                            Code = "role_management",
                            CreatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(5152),
                            Icon = "AccountArrowRight",
                            IsActive = true,
                            Name = "角色管理",
                            ParentId = 11,
                            Path = "/settings/roles",
                            SortOrder = 2,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(5152)
                        },
                        new
                        {
                            Id = 14,
                            Code = "menu_management",
                            CreatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(5155),
                            Icon = "Menu",
                            IsActive = true,
                            Name = "菜单管理",
                            ParentId = 11,
                            Path = "/settings/menus",
                            SortOrder = 3,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(5155)
                        });
                });

            modelBuilder.Entity("Backed.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3105),
                            Description = "Can view dashboard",
                            Name = "ViewDashboard",
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3106)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3109),
                            Description = "Can manage users",
                            Name = "ManageUsers",
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3110)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3111),
                            Description = "Can manage roles",
                            Name = "ManageRoles",
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3112)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3114),
                            Description = "Can manage products",
                            Name = "ManageProducts",
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3114)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3116),
                            Description = "Can manage menus",
                            Name = "ManageMenus",
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3116)
                        });
                });

            modelBuilder.Entity("Backed.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(2848),
                            Description = "Administrator role with full access",
                            Name = "Admin",
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(2849)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(2851),
                            Description = "Regular user role",
                            Name = "User",
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(2852)
                        });
                });

            modelBuilder.Entity("Backed.Domain.Entities.RoleMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("RoleId", "MenuId")
                        .IsUnique();

                    b.ToTable("RoleMenus");
                });

            modelBuilder.Entity("Backed.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3160),
                            PermissionId = 1,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3161)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3164),
                            PermissionId = 2,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3164)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3166),
                            PermissionId = 3,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3166)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3168),
                            PermissionId = 4,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3168)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3170),
                            PermissionId = 5,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3171)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3172),
                            PermissionId = 1,
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3173)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3174),
                            PermissionId = 4,
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(3175)
                        });
                });

            modelBuilder.Entity("Backed.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(5208),
                            Email = "admin@example.com",
                            IsActive = true,
                            PasswordHash = "21232f297a57a5a743894a0e4a801fc3",
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(5209),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Backed.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(5302),
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 21, 15, 84, DateTimeKind.Utc).AddTicks(5302),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Backed.Domain.Entities.Menu", b =>
                {
                    b.HasOne("Backed.Domain.Entities.Menu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Backed.Domain.Entities.RoleMenu", b =>
                {
                    b.HasOne("Backed.Domain.Entities.Menu", "Menu")
                        .WithMany("RoleMenus")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backed.Domain.Entities.Role", "Role")
                        .WithMany("RoleMenus")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Backed.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Backed.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backed.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Backed.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Backed.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backed.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backed.Domain.Entities.Menu", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("RoleMenus");
                });

            modelBuilder.Entity("Backed.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Backed.Domain.Entities.Role", b =>
                {
                    b.Navigation("RoleMenus");

                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Backed.Domain.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
