// <auto-generated />
using System;
using Backed.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backed.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251107085455_AddRoleMenuRelation")]
    partial class AddRoleMenuRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backed.Domain.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "dashboard",
                            CreatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7914),
                            Icon = "ViewDashboard",
                            IsActive = true,
                            Name = "仪表盘",
                            Path = "/dashboard",
                            SortOrder = 1,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7914)
                        },
                        new
                        {
                            Id = 2,
                            Code = "products",
                            CreatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7918),
                            Icon = "PackageVariant",
                            IsActive = true,
                            Name = "商品管理",
                            Path = "/products",
                            SortOrder = 2,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7919)
                        },
                        new
                        {
                            Id = 3,
                            Code = "product_list",
                            CreatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7922),
                            Icon = "FormatListBulleted",
                            IsActive = true,
                            Name = "商品列表",
                            ParentId = 2,
                            Path = "/products/list",
                            SortOrder = 1,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7922)
                        },
                        new
                        {
                            Id = 4,
                            Code = "product_category",
                            CreatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7925),
                            Icon = "Folder",
                            IsActive = true,
                            Name = "商品分类",
                            ParentId = 2,
                            Path = "/products/category",
                            SortOrder = 2,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7926)
                        },
                        new
                        {
                            Id = 5,
                            Code = "orders",
                            CreatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7928),
                            Icon = "ClipboardList",
                            IsActive = true,
                            Name = "订单管理",
                            Path = "/orders",
                            SortOrder = 3,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7929)
                        },
                        new
                        {
                            Id = 6,
                            Code = "order_list",
                            CreatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7932),
                            Icon = "FormatListBulleted",
                            IsActive = true,
                            Name = "订单列表",
                            ParentId = 5,
                            Path = "/orders/list",
                            SortOrder = 1,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7932)
                        },
                        new
                        {
                            Id = 7,
                            Code = "order_returns",
                            CreatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7935),
                            Icon = "PackageDown",
                            IsActive = true,
                            Name = "退货申请",
                            ParentId = 5,
                            Path = "/orders/returns",
                            SortOrder = 2,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7935)
                        },
                        new
                        {
                            Id = 8,
                            Code = "members",
                            CreatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7938),
                            Icon = "AccountMultiple",
                            IsActive = true,
                            Name = "会员管理",
                            Path = "/members",
                            SortOrder = 4,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7938)
                        },
                        new
                        {
                            Id = 9,
                            Code = "member_list",
                            CreatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7941),
                            Icon = "FormatListBulleted",
                            IsActive = true,
                            Name = "会员列表",
                            ParentId = 8,
                            Path = "/members/list",
                            SortOrder = 1,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7942)
                        },
                        new
                        {
                            Id = 10,
                            Code = "member_levels",
                            CreatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7945),
                            Icon = "Star",
                            IsActive = true,
                            Name = "会员等级",
                            ParentId = 8,
                            Path = "/members/levels",
                            SortOrder = 2,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7945)
                        },
                        new
                        {
                            Id = 11,
                            Code = "settings",
                            CreatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7948),
                            Icon = "Cog",
                            IsActive = true,
                            Name = "系统设置",
                            Path = "/settings",
                            SortOrder = 5,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7948)
                        },
                        new
                        {
                            Id = 12,
                            Code = "user_management",
                            CreatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7951),
                            Icon = "Account",
                            IsActive = true,
                            Name = "用户管理",
                            ParentId = 11,
                            Path = "/settings/users",
                            SortOrder = 1,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7952)
                        },
                        new
                        {
                            Id = 13,
                            Code = "role_management",
                            CreatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7955),
                            Icon = "AccountArrowRight",
                            IsActive = true,
                            Name = "角色管理",
                            ParentId = 11,
                            Path = "/settings/roles",
                            SortOrder = 2,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7955)
                        },
                        new
                        {
                            Id = 14,
                            Code = "menu_management",
                            CreatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7958),
                            Icon = "Menu",
                            IsActive = true,
                            Name = "菜单管理",
                            ParentId = 11,
                            Path = "/settings/menus",
                            SortOrder = 3,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7959)
                        });
                });

            modelBuilder.Entity("Backed.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7801),
                            Description = "Can view dashboard",
                            Name = "ViewDashboard",
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7801)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7804),
                            Description = "Can manage users",
                            Name = "ManageUsers",
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7805)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7807),
                            Description = "Can manage roles",
                            Name = "ManageRoles",
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7807)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7809),
                            Description = "Can manage products",
                            Name = "ManageProducts",
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7810)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7812),
                            Description = "Can manage menus",
                            Name = "ManageMenus",
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7812)
                        });
                });

            modelBuilder.Entity("Backed.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7589),
                            Description = "Administrator role with full access",
                            Name = "Admin",
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7590)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7593),
                            Description = "Regular user role",
                            Name = "User",
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7594)
                        });
                });

            modelBuilder.Entity("Backed.Domain.Entities.RoleMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("RoleId", "MenuId")
                        .IsUnique();

                    b.ToTable("RoleMenus");
                });

            modelBuilder.Entity("Backed.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7851),
                            PermissionId = 1,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7851)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7854),
                            PermissionId = 2,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7854)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7856),
                            PermissionId = 3,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7857)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7859),
                            PermissionId = 4,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7859)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7861),
                            PermissionId = 5,
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7862)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7864),
                            PermissionId = 1,
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7864)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7866),
                            PermissionId = 4,
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7866)
                        });
                });

            modelBuilder.Entity("Backed.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7981),
                            Email = "admin@example.com",
                            IsActive = true,
                            PasswordHash = "21232f297a57a5a743894a0e4a801fc3",
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(7981),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Backed.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(8028),
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 11, 7, 8, 54, 52, 816, DateTimeKind.Utc).AddTicks(8028),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Backed.Domain.Entities.Menu", b =>
                {
                    b.HasOne("Backed.Domain.Entities.Menu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Backed.Domain.Entities.RoleMenu", b =>
                {
                    b.HasOne("Backed.Domain.Entities.Menu", "Menu")
                        .WithMany("RoleMenus")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backed.Domain.Entities.Role", "Role")
                        .WithMany("RoleMenus")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Backed.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Backed.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backed.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Backed.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Backed.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backed.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backed.Domain.Entities.Menu", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("RoleMenus");
                });

            modelBuilder.Entity("Backed.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Backed.Domain.Entities.Role", b =>
                {
                    b.Navigation("RoleMenus");

                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Backed.Domain.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
